# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e31aa7bdb338377160a52ad570aed392674c8db664e15879bd50fafcd59058d7b8acdbe9b1f7ba9805e49a4f5ef6b175f8c7a31c2985deb70d811477b3e2cbbf

test:
  secret_key_base: bb08739535b504a8e8cd6adad2117b1a65c1dc06432802db8c76369976d143f016d8c57e152b96c4b835ae65778c514bf67f75f36e89098bbf19e30690f8de0a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
